logging:
  config:: classpath:tmp/logback-spring.xml




server:
  port: 8080



spring:
  #  jackson:
  #    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mylog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: com.codecrafter.typhoon.config.CustomUpperCaseSnakeCasePhysicalNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 50

    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
file:
  base:
    dir: ${user.home}/fileStore/




