#
logging:
  level:
    org:
    #      springframework.transaction.interceptor: trace
    #      hibernate.sql: debug
    root: info
    com.codecrafter.typhoon.config.filter.RequestLoggingFilter: Info




server:
  port: 8080



spring:
  #  jackson:
  #    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mylog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: com.codecrafter.typhoon.config.CustomUpperCaseSnakeCasePhysicalNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 50

    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
file:
  base:
    dir: ${user.home}/fileStore/








