logging:
  config: classpath:tmp/logback-spring.xml
  level:
    root: warn
  #####




server:
  port: 8080


spring:
  #  jackson:
  #    default-property-inclusion: non_null
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: com.codecrafter.typhoon.config.CustomUpperCaseSnakeCasePhysicalNamingStrategy
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  sql:
    init:
      mode: never
      schema-locations: classpath:dev/schema.sql
      data-locations: classpath:dev/data.sql
file:
  base:
    dir: ${user.home}/fileStore/




